logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/db-insurance?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
